### ISSUE TITLE
"Could not bind as LDAP admin" message

### ISSUE THREAD

**Issue by vivekakotkar26** [matomo-org/plugin-LoginLdap#135]
Hi Team,

We are facing issues in LDAP configuration. When we are loading user from LDAP server that gives error message `"Could not bind as LDAP admin".` please find the version detail mentioned below.

PHP Version                        : 5.6
PIWIK Version                     : 2.16.0
LoginLdap Plugin Version   : 3.3.0

Let me know if you want any information to resolve issue.

Thanks and Regards
Vivek Akotkar

Hi all ,
We have run script to check issue with php and we are getting following error message.

```
PHP Warning:  ldap_search(): Partial search results returned: Sizelimit exceeded in /var/www/html/ldap.php on line 23
Query count: 1000
```

Thanks and Regards
Vivek Akotkar

**Comment by vivekakotkar26** [comment]
Hi all ,
We have run script to check issue with php and we are getting following error message.

PHP Warning:  ldap_search(): Partial search results returned: Sizelimit exceeded in /var/www/html/ldap.php on line 23
Query count: 1000

Thanks and Regards
Vivek Akotkar

**Comment by nwoetzel** [comment]
I hope it is not too late to give a hint on your problem(s):
The first one hints on invalid credentials.
You might want to check if you can issue an ldapsearch command with the credentials you have configured with your ldap server.
<pre>
ldapsearch -h {Server URL} -p {Server Port} -b {Base DN} -D {LDAP Bind Username} -W
</pre>
and enter {LDAP Password}

If you see en error "ldap_bind: Invalid credentials (49)" than you need to check your credentials.

The second error you are seeing is, that your query is returning more than 1000 results. 1000 is the default size. It can be increased, but I am not sure if you can configure it in the plugin or in some ldaputils or php ldap configuration. But you might want to consider setting the {LDAP Search Filter} to "(objectClass=person)" so that you only retrieve persons.
This can be appended to the ldapsearch
<pre>
ldapsearch -h {Server URL} -p {Server Port} -b {Base DN} -D {LDAP Bind Username} -W "(objectClass=person)"
</pre>

I guess that your problem is not related to the plugin itself, but more on finding the proper configuration.

**Comment by mattab** [comment]
Thank you @nwoetzel for the help.

## Suggestions on fixing this issue

*  try prefixing the LDAP url by `ldaps://` and try again?
* Check the given admin credentials in Matomo's backend 
* also check the Ldap Searchfilter is correct eg. `(objectClass=person)`
* [check for LDAP connection issue.](https://github.com/matomo-org/plugin-LoginLdap/wiki/Troubleshooting#checking-for-an-ldap-server-configuration-issue) by issuing an `ldapsearch` command with the credentials you have configured with your ldap server.
