### ISSUE TITLE
Your Matomo account's password has just been changed

### ISSUE THREAD

**Issue by jgkirschbaum** [matomo-org/plugin-LoginLdap#180]
Since matomo version `3.9.0` every time signing on with an LDAP account, you always get an e-mail _'Your Matomo account's password has just been changed'_.

**Comment by arndbernstein** [comment]
Same problem here.

**Comment by Findus23** [comment]
Related to https://github.com/matomo-org/matomo/pull/14136

**Comment by diosmosis** [comment]
@tsteur Wonder if we can fix this by only sending the user info email changed if a password confirmation is required (so for automated use cases we don't send the email). What do you think?

**Comment by jgkirschbaum** [comment]
@diosmosis This would be a workaround, but what led to the problem?

**Comment by tsteur** [comment]
@diosmosis makes sense 👍

**Comment by diosmosis** [comment]
@jgkirschbaum LoginLdap updates the user information, and when the password changes an email is sent notifying users. The problem is that 1) the password change email is sent even if changing the password to the same password since we don't have the plain text password to compare and 2) LoginLdap updates to the same password. Actually, thinking about it, there's probably a better fix. Thanks for asking the question, @jgkirschbaum !

**Comment by diosmosis** [comment]
@jgkirschbaum would you be able to test if https://github.com/matomo-org/matomo/pull/14240 solves the problem for you?

**Comment by jgkirschbaum** [comment]
@diosmosis yes, but not before tomorrow morning.

**Comment by arndbernstein** [comment]
@diosmosis the patch works for us. No more notifications after signing in.

**Comment by diosmosis** [comment]
Thanks for letting us know @arndbernstein !

**Comment by jgkirschbaum** [comment]
@diosmosis patch works for https://github.com/matomo-org/matomo/pull/14240#discussion_r267211422
