### ISSUE TITLE
Can not enable Two-factor Authentication for LDAP users

### ISSUE THREAD

**Issue by ibro0** [matomo-org/plugin-LoginLdap#181]
Hi, as the title stated, i can not enable Two-factor Authentication for the users that have been added using LDAP. When i click "ENABLE TWO-FACTOR AUTHENTICATION" i get transferred to another page asking for password "Confirm your password to continue" this issue is when i enter the password it says its wrong. for all LDAP users. it works perfect for local users.
Pics attached.
![2019-04-02 14_27_01-Sign in - Matomo](https://user-images.githubusercontent.com/16525392/55402098-433d8180-555b-11e9-9db7-30c9f151c444.png)

**Comment by tsteur** [comment]
LoginLdap will likely need to disable TwoFA or somehow disable the password check here.

**Comment by manusfreedom** [comment]
Anynews about this problem?

**Comment by manusfreedom** [comment]
Workaround but not a solution, we are able to use 2FA :
* force 2FA (Require two-factor authentication for everyone)
* each LDAP user set their 2FA
* disable 2FA required

After that our user can use LDAP login/password and the 2FA.

**Comment by paladox** [comment]
Also bump too, this is a very useful feature (an added protection).

**Comment by tsteur** [comment]
@paladox I suppose this is using the latest 3.X version?

@diosmosis I remember a few months back you mentioned something about the password verifier and ldap. Any chance this was maybe fixed in Matomo 4?

When does above error happen? Is that happen directly when you click on "set up 2FA" and you can't verify the password?

**Comment by diosmosis** [comment]
This seems vaguely familiar, but I can't quite remember. I can try to test it on 4.x-dev.

**Comment by paladox** [comment]
@tsteur yup. Also from what i've herd it's when trying to use 2fa, existing users who have 2fa can still use it.

**Comment by jonquandt** [comment]
Related test case for this issue-- if you have the LoginLDAP module enabled, and 2FA setup via the force all users workaround, you cannot configure a different device via the UI. 

Expected workflow:
- Login to Matomo using 2FA from old device
- Go to account settings
- scroll to two factor authentication
- click on Enable on a Different Device
- using new device/authenticator app, scan the QR code, enter the one-time pin from device to confirm and save

What Happens
- Login to Matomo using 2FA from old device
- Go to account settings
- scroll to two factor authentication
- click on Enable on a Different Device
- get error that Login module is not configured.

I'm guessing this means we need to disable 2FA from the superuser/admin side, and then force enable it again for all users in order to migrate to a new authenticator/device.

**Comment by jonquandt** [comment]
Update: I was able to change to a different 2FA client/device by asking the super user to reset my 2FA profile using the instructions here:

https://matomo.org/faq/how-to/faq_27248

That's while 2FA was forced for all users.


Including in case it's helpful for others that find this when trying to find a solution for 2FA/loginLdap
